compiler:
    - gcc
    - clang

language: objective-c

before_install:
 - brew update && brew outdated cmake || brew upgrade cmake
script:
 - export REV=dirty-$(git describe --always)
 - wget https://launchpad.net/gcc-arm-embedded/4.9/4.9-2015-q2-update/+download/gcc-arm-none-eabi-4_9-2015q2-20150609-src.tar.bz2 --no-check-certificate
 - tar xjf gcc-arm-none-eabi-4_9-2015q2-20150609-src.tar.bz2
 - mv gcc-arm-none-eabi-4_9-2015q2-20150609/src/* ./src/
 - rm src/newlib.tar.bz2
 - cd src/
 - find . -name '*.tar.*' | xargs -I% tar -xf %
 - patch -p0 < ../vita.patch
 - cd ..
 - wget http://www.digip.org/jansson/releases/jansson-2.7.tar.gz --no-check-certificate
 - tar xf jansson-2.7.tar.gz
 - mv jansson-2.7 src/
 - ./build-prerrequisites.sh
 - ./build-toolchain.sh
env:
 global:
  - TOP=$PWD
  - PREFIX=$TOP/dist
