os:
  - linux
  - osx

compiler:
    - gcc

language: cpp
install:
    - if [ "`echo $CXX`" == "g++" ]; then export CXX=g++-4.8; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - apt-src
    - scons
    - mingw32-runtime
    - p7zip-full
    - gawk
    - gzip
    - perl
    - autoconf
    - m4
    - automake
    - libtool
    - libncurses5-dev
    - gettext
    - gperf
    - dejagnu
    - expect
    - tcl
    - autogen
    - guile-1.6
    - flex
    - flip
    - bison
    - tofrodos
    - texinfo
    - gcc-multilib
    - libgmp3-dev
    - libmpfr-dev
    - debhelper
    - texlive
    - texlive-extra-utils
# - brew update && brew outdated cmake || brew upgrade cmake
script:
 - export REV=dirty-$(git describe --always)
 - wget https://launchpad.net/gcc-arm-embedded/4.9/4.9-2015-q2-update/+download/gcc-arm-none-eabi-4_9-2015q2-20150609-src.tar.bz2 --no-check-certificate
 - tar xjf gcc-arm-none-eabi-4_9-2015q2-20150609-src.tar.bz2
 - mv gcc-arm-none-eabi-4_9-2015q2-20150609/src/* ./src/
 - rm src/newlib.tar.bz2
 - cd src/
 - find . -name '*.tar.*' | xargs -I% tar -xf %
 - patch -p0 < ../vita.patch
 - cd ..
 - wget http://www.digip.org/jansson/releases/jansson-2.7.tar.gz --no-check-certificate
 - tar xf jansson-2.7.tar.gz
 - mv jansson-2.7 src/
 - chmod +x *.sh
 - ./build-phase1.sh
 - ./build-phase2.sh
env:
 global:
  - TOP=$PWD
  - PREFIX=$TOP/dist
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-$TRAVIS_OS_NAME-0.1-v$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER - $TRAVIS_OS_NAME"
  - git push -q https://$TAGPERM@github.com/frangarcj/vitasdk-buildscripts --tags
deploy:
  provider: releases
  api_key: $OAUTH
  file_glob: true
  file: "pkg/*.tar.bz2"
  skip_cleanup: true
  on:
    tags: false
    all_branches: true

branches:
  except:
    - /^*-v[0-9]/
