os:
  - osx
env:
  - M32=" "
matrix:
  exclude:
    - os: osx
      env: M32="-m32"
osx_image: xcode8

language: cpp

before_install:
  - brew install homebrew/dupes/ncurses
addons:
script:
 - export REV=dirty-$(git describe --always)
 - chmod +x *.sh
 - ./build.sh
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-$TRAVIS_OS_NAME-v$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$TAGPERM@github.com/frangarcj/vitasdk-buildscripts --tags
deploy:
  provider: releases
  api_key: $OAUTH
  file_glob: true
  file: "pkg/*"
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
branches:
  except:
    - /^*-v[0-9]/
