os:
  - linux

language: cpp

before_install:
  - sudo apt-get install -y autoconf automake bison build-essential bzip2  cmake flex git libgmp3-dev libjansson-dev libncurses5-dev libtool libzip-dev pkg-config python python-dev subversion  texinfo wget zlib1g-dev xutils-dev g++
addons:
script:
 - export REV=dirty-$(git describe --always)
 - chmod +x *.sh
 - ./build.sh
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-$TRAVIS_OS_NAME-v$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$TAGPERM@github.com/frangarcj/vitasdk-buildscripts --tags
deploy:
  provider: releases
  api_key: $OAUTH
  file_glob: true
  file: "pkg/*"
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
branches:
  except:
    - /^*-v[0-9]/
