os:
  - osx
env:
  - M32=" "
matrix:
  exclude:
    - os: osx
      env: M32="-m32"

compiler:
    - apple-gcc42

language: cpp

addons:
script:
 - export REV=dirty-$(git describe --always)
 - wget https://launchpad.net/gcc-arm-embedded/4.9/4.9-2015-q3-update/+download/gcc-arm-none-eabi-4_9-2015q3-20150921-src.tar.bz2 --no-check-certificate
 - tar xjf gcc-arm-none-eabi-4_9-2015q3-20150921-src.tar.bz2
 - mv gcc-arm-none-eabi-4_9-2015q3-20150921/src/* ./src/
 - rm src/newlib.tar.bz2
 - cd src/
 - find . -name '*.tar.*' | xargs -I% tar -xf %
 - cd ..
 - wget http://www.digip.org/jansson/releases/jansson-2.7.tar.gz --no-check-certificate
 - tar xf jansson-2.7.tar.gz
 - mv jansson-2.7 src/
 - wget http://nih.at/libzip/libzip-1.1.3.tar.gz --no-check-certificate
 - tar xf libzip-1.1.3.tar.gz
 - mv libzip-1.1.3 src/
 - patch -p1 < vita.patch
 - chmod +x *.sh
 - ./build-prerequisites.sh
 - ./build-toolchain.sh
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-0.1-v$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"; fi
  - git push -q https://$TAGPERM@github.com/frangarcj/vitasdk-buildscripts --tags; fi
deploy:
  provider: releases
  api_key: $OAUTH
  file_glob: true
  file: "pkg/*"
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
branches:
  except:
    - /^*-v[0-9]/
