os:
  - osx
env:
  - M32=" "
matrix:
  exclude:
    - os: osx
      env: M32="-m32"
osx_image: xcode8

language: cpp

before_install:
  - brew update
  - brew outdated autoconf || brew upgrade autoconf
  - brew outdated automake || brew upgrade automake
  - brew outdated bison || brew upgrade bison
  - brew outdated flex || brew upgrade flex
  - brew outdated texinfo || brew upgrade texinfo
  - brew install homebrew/dupes/ncurses
  - brew outdated wget || brew upgrade wget
  - brew outdated libelf || brew upgrade libelf
  - brew outdated zlib || brew upgrade zlib
  - brew outdated libtool || brew upgrade libtool
  - brew outdated gmp || brew upgrade gmp
  - brew outdated openssl || brew upgrade openssl
  - brew outdated mpfr || brew upgrade mpfr
  - brew outdated libmpc || brew upgrade libmpc
  - brew outdated unrar || brew upgrade unrar
  - brew outdated subversion || brew upgrade subversion
  - brew outdated bzip2 || brew upgrade bzip2
  - brew outdated cmake || brew upgrade cmake
  - brew outdated go || brew upgrade go
addons:
script:
 - export REV=dirty-$(git describe --always)
 - chmod +x *.sh
 - ./build.sh
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-$TRAVIS_OS_NAME-v$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$TAGPERM@github.com/frangarcj/vitasdk-buildscripts --tags
deploy:
  provider: releases
  api_key: $OAUTH
  file_glob: true
  file: "pkg/*"
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
branches:
  except:
    - /^*-v[0-9]/
